### PR TITLE
Multiple bugfixes cherry-picked from LuaJIT issues and PRs

### PR DESCRIPTION
**Pull request by siddhesh**
This is a set of patches I incorporated from the official LuaJIT repo since they were lying there unattended.

### CODE REVIEW

**Comment by XVilka** [comment]
Isn't the better course of action now switch to the [MoonJIT](https://github.com/moonjit/moonjit) instead?

**Comment by agentzh** [comment]
@XVilka No, we need total control over this branch and I'm not a big fan of a real fork, to be honest.

**Comment by siddhesh** [comment]
I believe all but the OpenBSD patch were incorporated by Mike.  I'll rebase and post the last remaining patch.

On the subject of using moonjit, direct use is currently not possible due to the extensions that openresty uses.  There's a case for using the moonjit v2.1 branch as the base instead of Mike's repo since we're doing the same thing as luajit2 as far as tracking LuaJIT/LuaJIT is concerned.  That will allow openresty/luajit2 to focus on only its extensions.  Does that sound reasonable @agentzh ?

**Comment by agentzh** [comment]
@siddhesh Thanks for taking care of the remaining patches. We'll look at the new pull requests. Preferably atomic pull requests for each change. That helps the code review and editing process.

I still prefer using Mike's repo as the upstream instead of moonjit.

**Comment by siddhesh** [comment]
Got it, I think we have a better plan going in #80 to manage this.  Lets do the patches first and take things as they evolve.

**Comment by siddhesh** [comment]
This is obsolete. Closing.

**Pull request closed without merging**
