### PR TITLE
Add support for LoongArch64

### PR DESCRIPTION
**Pull request by sophie-zhao**
Hi, @agentzh

As we know, there are many users using openresty, and luajit is used in openresty, can you review our code?

This patchset is adding basic LoongArch64 support in LuaJIT (interpreter and JIT-compiler code).

LoongArch is a new RISC ISA, which is independently designed by Loongson Technology. LoongArch includes a reduced 32-bit version (LA32R), a standard 32-bit version (LA32S) and a 64-bit version (LA64).

Loongson and LoongArch documentations:
https://github.com/loongson/LoongArch-Documentation

The ISAs, ABIs and OS we support are:
ISA: LoongArch64
ABI: LP64d
OS: Linux

Open-source tool chain (Binutils, Gcc and glibc) are already upstream.

We have verified the support of luajit/LoongArch64 in openresty locally.

### CODE REVIEW

**Comment by abner-chenc** [comment]
Gentle ping.

**Comment by zhuizhuhaomeng** [comment]
We don't want to maintain that many architectures.
You can fork your own repo for those who are interested in loongArch64.

**Comment by sophie-zhao** [comment]
Hi， @zhuizhuhaomeng 

Now there are many users using openresty on the loongarch64 architecture. It would be best if the loongarch64 architecture can be supported on openresty/luajit2. Moreover, the kernel, Open-source tool chain (Binutils, Gcc and glibc) are already upstream.

In addition, we are happy to help maintain the code and provide CI machines to ensure the quality of testing.

So you don't have to worry about lack of manpower or environment.

**Comment by agentzh** [comment]
@sophie-zhao will you please convince Mike Pall to merge it in the upstream LuaJIT? We sync from the upstream LuaJIT periodically.

**Comment by sophie-zhao** [comment]
We also think it would be better to merge to the upstream LuaJIT, but Mike is too busy and we are trying our best to contact him. If it cannot be merged into the upstream LuaJIT (the worst case), we hope that the openresty/luajit2 can accept a new port, which is not a bad thing for both of us.

**Comment by wdlkmpx** [comment]
> We also think it would be better to merge to the upstream LuaJIT, but Mike is too busy and we are trying our best to contact him. If it cannot be merged into the upstream LuaJIT (the worst case), we hope that the openresty/luajit2 can accept a new port, which is not a bad thing for both of us.

Yeah I noticed Alpine Linux is using this repo instead of upstream. I see in the other PR upstream rejected this ruthlessly, perhaps in this repo, people can show a little bit of kindness.
As you say, your team will fix the issues and bugs that arise on loongarch64... if this assurance is not enough, then nothing is..

**Comment by agentzh** [comment]
@wdlkmpx If it were merged, then we would have to maintain it. And your changes also touched some existing source files, which *might* break other architectures accidentally. That was why I asked you to contact Mike Pall instead. We also don't want to deal with all the merge conflicts we don't quite understand every time we try to sync with Mike's upstream version in the future.

**Comment by zhhzhhz** [comment]
https://github.com/loongson/luajit2
good job!

**Pull request closed without merging**
