### PR TITLE
feature: implemented the luaL_checkcdataptr C API for converting LuaJIT cdata pointer object on Lua stack to pointer.

### PR DESCRIPTION
**Pull request by dndx**
Right now LuaJIT does not expose any C API for C code to unwrap boxed `cdata` objects from the stack. This API adds support for unwrapping pointer type `cdata` objects.

### CODE REVIEW

**Comment by agentzh** [comment]
Why do we need this? Any concrete use cases? The cdata type is designed to be used with FFI, not the traditional Lua C API context.

**Comment by dndx** [comment]
@agentzh https://github.com/openresty/lua-nginx-module/pull/1599

**Comment by agentzh** [comment]
Hmm, that looks more like a hack since we lose the type information of the incoming cdata arguments. I think the right way is to re-implement the `sslhandshake` method as a pure FFI-based one instead (or better, the whole cosocket API). I don't feel comfortable at all with adding this C function to the existing LuaJIT ABI.

**Comment by dndx** [comment]
Superseded by: https://github.com/openresty/lua-nginx-module/pull/1602.

**Pull request closed without merging**
