### PR TITLE
feature: export the key_sentinel.

### LINKED ISSUE #153: pcall problem when calling require
Hello!

Tipically, for versions compatibility consideration, we could use pcall to catch exception of require.

But I have found a strange luajit problem when using pcall and require, especially when ffi involves.

**Minimum reproduction configuation:**

1. conf/nginx.conf

```console
events {}

http{
    lua_package_path  ';;$prefix/lua/?.lua';
    init_by_lua_block {
        local has_a, a
        has_a, a= pcall(require, "a")
        if not has_a then
            ngx.log(ngx.ERR, "failed to load a: ", a)
        end

        has_a, a = pcall(require, "a")
        if not has_a then
            ngx.log(ngx.ERR, "failed to load a again: ", a)
        else
            ngx.log(ngx.ERR, "type(a)=", type(a), " a=", a)
        end
    }
}
```

2. lua/a.lua

```lua
local ffi = require("ffi")

local _M = {}

ffi.cdef[[
int xxxx();
]]

local function get_caches_array()
    return tonumber(ffi.C.xxxx())
end

local a = get_caches_array()

_M.a = a
_M.get_caches_array = get_caches_array

return _M
```

**Expectation:**

Since a.lua contains a non defined xxxx ffi function, I expect everytime we call `pcall(require, "a")`, a false and an error message retuns.

**behavior of diffirent version**

openresty-1.13.6.2 meets my expectation, output:

```console
[root@localhost pcall_error]# /usr/local/openresty-1.13.6.2/nginx/sbin/nginx  -p .
nginx: [error] [lua] init_by_lua:5: failed to load a: .//lua/a.lua:10: /usr/local/openresty-1.13.6.2/luajit/lib/libluajit-5.1.so.2: undefined symbol: xxxx
nginx: [error] [lua] init_by_lua:10: failed to load a again: loop or previous error loading module 'a'
```

From openresty-1.15.8.1, things becom strange, and have diffirent result in diffirent version.

openresty-1.15.8.1:
```console
nginx: [error] [lua] init_by_lua:5: failed to load a: .//lua/a.lua:10: /usr/local/openresty-1.15.8.1/luajit/lib/libluajit-5.1.so.2: undefined symbol: xxxx
nginx: [error] [lua] init_by_lua:12: type(a)=userdata a=null
```

openresty-1.15.8.3:
```console
nginx: [error] [lua] init_by_lua:5: failed to load a: .//lua/a.lua:10: /usr/local/openresty-1.15.8.3/luajit/lib/libluajit-5.1.so.2: undefined symbol: xxxx
nginx: [error] [lua] init_by_lua:12: type(a)=userdata a=null
```

openresty-1.19.9.1:

```console
nginx: [error] [lua] init_by_lua:5: failed to load a: .//lua/a.lua:10: /usr/local/openresty/luajit/lib/libluajit-5.1.so.2: undefined symbol: xxxx
nginx: [error] [lua] init_by_lua:12: type(a)=number a=-5.6817549271743e-322
```

I'm not familiar with luajit internals, so have this feedback.

Thanks.

### PR DESCRIPTION
**Pull request by zhuizhuhaomeng**
fix https://github.com/openresty/luajit2/issues/153

### CODE REVIEW

**Comment by XmiliaH** [comment]
Why not use `package.loaded[...]` at the top level of `resty/core/base.lua` to get the sentinel? This would not require so many changes.

**Comment by zhuizhuhaomeng** [comment]
> resty/core/base.lua

I have added the key_sentinel at package.loaded.package.key_sentinel before.
but need to change another repo(https://github.com/openresty/luajit2-test-suite).

I think you you are right, I will change back to the original method.

**Comment by XmiliaH** [comment]
> I have added the key_sentinel at package.loaded.package.key_sentinel before.

You do not need to add key_sentinel. When running on the top level of `resty/core/base.lua` it can be found in `package.loaded['resty.core.base']`. I used `(...)` since the first arg of the chunk is its name in the `resty/core/base.lua` case this would be `resty.core.base`.

**Comment by zhuizhuhaomeng** [comment]
@XmiliaH  update, please review again

**Comment by XmiliaH** [comment]
I think the changes to luajit2 are not required. I would replace
```lua
local function my_require(name)
	local mod = pkg_loaded[name]
	if mod then
		return mod
	end
	return orig_require(name)
end
```
with
```lua
local key_sentinel = pkg_loaded[...]
local error = error

local function my_require(name)
	local mod = pkg_loaded[name]
	if mod then
		if mod == key_sentinel then
			error("loop or previous error loading module '" .. name .. "'")
		end
		return mod
	end
	return orig_require(name)
end
```
in `resty/core/base.lua`.
This should fix the problem with less changes.

**Comment by zhuizhuhaomeng** [comment]
local key_sentinel = pkg_loaded[...]  is nil.
how would that work?

**Comment by XmiliaH** [comment]
> local key_sentinel = pkg_loaded[...] is nil.

How did you test that? When I do:
*test.lua*
```lua
print(package.loaded[...])
```
and run
```bash
luajit -e 'require("test")'
```
I get the sentinel printed as it is inserted in to `package.loaded` before the chunk is executed and replaced if the chunk completes normally. So during the execution of the chunk the sentinel can be found in the table.

**Comment by zhuizhuhaomeng** [comment]
I test with the following code.

```
luajit -e "print(package.loaded[...])"
```

but your code works when I replace it with mime and run the test case.

**Comment by XmiliaH** [comment]
Your test did not work since the `package.loaded[...]` only works in Lua files which are loaded via `require`, but this should be the case for `resty/core/base.lua`.

**Comment by zhuizhuhaomeng** [comment]
I test with the following code.
I will close this PR.

**Pull request closed without merging**
