### PR TITLE
Change: Resolve luaL_newstate() return NULL in ppc64le issue

### PR DESCRIPTION
**Pull request by ManirajDeivendran**
Solution for issue: #122

### CODE REVIEW

**Comment by krishvoor** [comment]
@xiaocang - Can you kindly take a look at this PR.
This ensures test cases to pass on `openresty/openresty` for ppc64le architecture.

**Comment by ManirajDeivendran** [comment]
@zhuizhuhaomeng, If possible, please provide your review for this PR as well.

**Comment by zhuizhuhaomeng** [comment]
> @zhuizhuhaomeng, If possible, please provide your review for this PR as well.

I think it is better to add the #ifdef LJ_ARCH_PPC_ELFV2 macro guard to reduce the impact.
Let's ask Guy Menanteau <menantea@fr.ibm.com> to help with the review.
is he your colleague ? @ManirajDeivendran

**Comment by menantea** [comment]
If I am not wrong, LJ_ARCH_PPC_ELFV2 depend of LJ_64 in src/lj_arch.h 
based on this, I don't know if it could have a side effect on other 64 bits arches but the patch using LJ_64 address at least the ppc64le architecture. If this patch should address ppc64le arch and only this one,  LJ_ARCH_PPC_ELFV2 is more secure to avoid side effect.

**Comment by ManirajDeivendran** [comment]
Hi @menantea ,

Thanks for your comments.

Hi @zhuizhuhaomeng,

According to the review comments modified the code to add the #ifdef LJ_ARCH_PPC_ELFV2 macro guard to reduce the impact.
Please provide your comments if any.

Thanks.

**Comment by ManirajDeivendran** [comment]
Hi @zhuizhuhaomeng,

Please provide your comments if any.

Thanks.

**Review by zhuizhuhaomeng — APPROVED** [review]

**Comment by zhuizhuhaomeng** [comment]
> Hi @zhuizhuhaomeng,
> 
> Please provide your comments if any.
> 
> Thanks.

sorry for the late reply. 
I will ask @doujiang24 if we could merge this.

**Comment by zhuizhuhaomeng** [comment]
> Hi @zhuizhuhaomeng,
> 
> Please provide your comments if any.
> 
> Thanks.

merged already

**Comment by ManirajDeivendran** [comment]
Thank you very much @zhuizhuhaomeng , @menantea , @xiaocang and @krishvoor for your support.

**Pull request merged**
